name: Continuos Deployment

on:
  push:
    branches: [ master ]

jobs:
  continuos-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile

      - name: Lint code
        run: yarn lint

      - name: Lint CSS
        run: yarn lint

      - name: Test
        run: CI=true yarn test -- --colors --coverage

      - name: Build
        run: CI=true yarn build

      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=build --prod
