name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create build version
        id: createbuildversion
        run:
          echo "::set-output name=buildversion::$(date +'%y.%m%d').${{ github.run_number }}"

      - name: Check build version
        run:
          echo "Using version ${{steps.createbuildversion.outputs.buildversion}}"

      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile

      - name: Lint code
        run:
          yarn lint

      - name: Lint css
        run:
          yarn lint:css

      - name: Test
        run: yarn test --colors --coverage

      - name: Build
        run: yarn build
        env:
          REACT_APP_RELATIVE_ROOT: /craks-1 # NOTE: Ensure no trailing '/'
          REACT_APP_VERSION: ${{steps.createbuildversion.outputs.buildversion}}
          REACT_APP_AI_INSTRUMENTATION_KEY: ${{ secrets.AZURE_CREDENTIALS_KSAPPLICATIONS_AI_KEY }}

      - name: Set PWA scope
        uses: benday-inc/set-property-value-in-appsettings@main
        with:
          pathtosettingsfile: './build/manifest.json'
          keyname1: 'scope'
          valuetoset: '/craks-1/'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_KSAPPLICATIONS_STORAGE }}

      - name: Deploy
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az storage blob upload-batch --account-name ksapplications -d '$web\craks-1' -s ./build

      - name: Azure Logout
        run: |
              az logout
