name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  continuos-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create build version
        id: createbuildversion
        run: echo "::set-output name=buildversion::$(date +'%y.%m%d').${{ github.run_number }}"

      - name: Generate version number
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile

      - name: Lint code
        run:
          yarn lint
          yarn lint:css

      - name: Test
        run: yarn test --colors --coverage

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_KSAPPLICATIONS_STORAGE }}

      - name: Build en
        run: yarn build
        env:
          REACT_APP_RELATIVE_ROOT: /cracks-1 # NOTE: Ensure no trailing '/'
          REACT_APP_VERSION: ${{steps.createbuildversion.outputs.buildversion}}

      - name: Set PWA scope for en
        uses: benday-inc/set-property-value-in-appsettings@main
        with:
          pathtosettingsfile: './build/manifest.json'
          keyname1: 'scope'
          valuetoset: '/cracks-1/'

      - name: Deploy en
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az storage blob upload-batch --account-name ksapplications -d '$web\cracks-1' -s ./build

      - name: Azure Logout
        run: |
              az logout
